-- Inventario general de insumos (hotelería/bodega) — aparte del inventario
-- clínico automático de máscara/elásticos/GUM/botón. Una bodega por sede,
-- réplica del flujo del Excel: catálogo compartido de ítems por categoría, y
-- un "período" de conteo por sede (cuando se hace inventario físico) con
-- entrega1/entrega2 (consumo), entradas (pedidos que llegaron) y pedido (lo
-- que falta pedir) por ítem.

create table insumos_generales_catalogo (
  id uuid primary key default gen_random_uuid(),
  categoria text not null,
  nombre text not null,
  orden integer not null default 0,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table insumos_generales_periodos (
  id uuid primary key default gen_random_uuid(),
  sede_id uuid not null references sedes(id),
  etiqueta text not null, -- ej. "Agosto 2026"
  fecha_inicio date not null default current_date,
  fecha_fin date,
  cerrado boolean not null default false,
  created_at timestamptz not null default now()
);
create index idx_insumos_generales_periodos_sede on insumos_generales_periodos (sede_id, fecha_inicio desc);

create table insumos_generales_movimientos (
  id uuid primary key default gen_random_uuid(),
  periodo_id uuid not null references insumos_generales_periodos(id) on delete cascade,
  catalogo_id uuid not null references insumos_generales_catalogo(id),
  inventario_inicial integer not null default 0,
  entrega1 integer not null default 0,
  entrega2 integer not null default 0,
  entradas integer not null default 0,
  pedido integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (periodo_id, catalogo_id)
);

alter table insumos_generales_catalogo enable row level security;
alter table insumos_generales_periodos enable row level security;
alter table insumos_generales_movimientos enable row level security;

create policy insumos_gen_catalogo_select on insumos_generales_catalogo for select using (auth.uid() is not null);
create policy insumos_gen_catalogo_write on insumos_generales_catalogo for all using (fn_es_admin()) with check (fn_es_admin());

create policy insumos_gen_periodos_select on insumos_generales_periodos for select using (fn_es_admin() or sede_id = fn_perfil_sede());
create policy insumos_gen_periodos_insert on insumos_generales_periodos for insert with check (fn_es_admin() or sede_id = fn_perfil_sede());
create policy insumos_gen_periodos_update on insumos_generales_periodos for update using (fn_es_admin() or sede_id = fn_perfil_sede());

create policy insumos_gen_movimientos_select on insumos_generales_movimientos for select using (
  fn_es_admin() or exists (select 1 from insumos_generales_periodos p where p.id = periodo_id and p.sede_id = fn_perfil_sede())
);
create policy insumos_gen_movimientos_insert on insumos_generales_movimientos for insert with check (
  fn_es_admin() or exists (select 1 from insumos_generales_periodos p where p.id = periodo_id and p.sede_id = fn_perfil_sede())
);
create policy insumos_gen_movimientos_update on insumos_generales_movimientos for update using (
  fn_es_admin() or exists (select 1 from insumos_generales_periodos p where p.id = periodo_id and p.sede_id = fn_perfil_sede())
);

-- Catálogo inicial (172 ítems, tal como venía en el Excel de control).
insert into insumos_generales_catalogo (categoria, nombre, orden) values
('Aparatos','Yeso (Bulto)',1),
('Aparatos','Mascara Facial',2),
('Aparatos','Ionomero Cementar Aparatos',3),
('Aparatos','Elasticos (Elefante) Bolsa*15',4),
('Aparatos','Cera Rosada',5),
('Aparatos','Alginato (Orthoprint)',6),
('Aparatos','Discos de carburo',7),
('Aparatos','Bolsas laboratorio',8),
('Aparatos','Resina Ortodoncia',9),
('Aparatos','Llaves aparatologia',10),
('Aparatos','Topes tumba bandas',11),
('Cirugía','Fresa CX',12),
('Cirugía','Eyectores CX',13),
('Cirugía','Batas CX',14),
('Endodoncia','Oxido de Zinc (175GM)',15),
('Endodoncia','Limas (6,8,10,15, 20, 25)',16),
('Endodoncia','Eugenol',17),
('Endodoncia','Dentofar',18),
('Endodoncia','Endoice',19),
('Endodoncia','Clorhexidina al 2%',20),
('Endodoncia','Medicamentos CTZ',21),
('Endodoncia','Lentulos',22),
('Endodoncia','Tira nervios',23),
('Endodoncia','Puntas para irrigar',24),
('Endodoncia','Endozecrya',25),
('Exodoncia','Sutura Vicryl o Azucryl (4 ceros)*Unidad',26),
('Exodoncia','Ratones (caja*72)',27),
('Exodoncia','Gasas',28),
('Exodoncia','Gaharocaina (Roxicaina sustituto)',29),
('Exodoncia','Anestesia Infiltrativas New Stetic',30),
('General','Tapabocas',31),
('General','Guantes vinilo / nitrilo S',32),
('General','Guantes Latex XS',33),
('General','Guantes Latex M',34),
('General','Guantes vinilo / nitrilo XS',35),
('General','Guantes vinilo / nitrilo M',36),
('General','Seda Dental',37),
('General','Hojas de Bisturi',38),
('General','Aguja Pediatrica',39),
('General','Guardian 0,5 lts',40),
('General','Eyectores',41),
('General','Algodón en Rollo',42),
('General','Clorhexidina Grande (Perio Aid)',43),
('General','Lunas de espejo Superdent caja *12',44),
('General','Jeringas*100',45),
('Profiflúor','Fluor Clinpro',46),
('Profiflúor','Detarfar (Grande)',47),
('Profiflúor','Cepillo de Profilaxis*100',48),
('Restauraciones','Resina fluida A1 (Teric N''ceram) / Opalis',49),
('Restauraciones','Resina fluida A2 (Tetrci N''ceram) / Opalis',50),
('Restauraciones','Resina A1 (Tetrci N''ceram)',51),
('Restauraciones','Tiras de Millar',52),
('Restauraciones','Retracfar',53),
('Restauraciones','Lijas Metalicas',54),
('Restauraciones','Resina P60 B2',55),
('Restauraciones','Ketac Molar',56),
('Restauraciones','Resina A2 (Tetrci N''ceram)',57),
('Restauraciones','Coltosol',58),
('Restauraciones','Microaplicadores',59),
('Restauraciones','Papel Articular',60),
('Restauraciones','Ionosit / Iliner',61),
('Restauraciones','Discos Soflex rojo',62),
('Restauraciones','Discos Soflex naranjado',63),
('Restauraciones','Bonding FGM Universal',64),
('Restauraciones','Banda metàlica',65),
('Restauraciones','Acido Fosforico',66),
('Restauraciones','Fresa Redonda pequeña',67),
('Restauraciones','Fresa Redonda mediana',68),
('Restauraciones','Fresa Redonda grande',69),
('Restauraciones','Llama amarilla',70),
('Restauraciones','Llama roja',71),
('Restauraciones','Interproximal roja',72),
('Restauraciones','Interproximal amarilla',73),
('Restauraciones','Pulidores blancos',74),
('Restauraciones','Enhace Copa',75),
('Restauraciones','Enhace llama',76),
('Restauraciones','Mandril',77),
('Restauraciones','Sellante',78),
('Restauraciones','Formas Plásticas (Caja)',79),
('Ortodoncia','Brackets rot rooth 0,22',80),
('Insumos','Vasos (Paquete x50)',81),
('Insumos','Servilletas',82),
('Insumos','Scott',83),
('Insumos','Botones',84),
('Insumos','Botones con Cadeneta',85),
('Aparatos','Hilo Elástico',86),
('Insumos','Ligaduras',87),
('Varios','Hipoclorito',88),
('Dispositivo médico','Vaselina',89),
('Dispositivo médico','Pimpollos',90),
('Dispositivo médico','Teflón',91),
('Dispositivo médico','Separadores interproximales',92),
('Esterilización','Agua desionizada',93),
('Esterilización','Germidina',94),
('Esterilización','Glutadina (holandina)',95),
('Esterilización','Papel Chicle',96),
('Esterilización','Papel Crepado (100 MTS)',97),
('Esterilización','Integrador Químico',98),
('Esterilización','Cinta esterilometro',99),
('Esterilización','Bolsa esterilizar pequeña',100),
('Esterilización','Bolsa esterilizar 90mm*260mm',101),
('Esterilización','Bolsa para esterilizar cubetas',102),
('Esterilización','Alkazyme /Bonzyme/prokizyme',103),
('Esterilización','Alcohol',104),
('Esterilización','Klorkleen',105),
('Esterilización','Cinta para marcar instrumental',106),
('Varios','GUM',107),
('Varios','Juguetes',108),
('Varios','Pilas (Teclado AA y AAA)',109),
('Varios','Pilas pesa (redonda) Ref. 20-32',110),
('Varios','Cremas y Cepillos',111),
('Varios','Aromatizador de ambiente',112),
('Varios','Tóner impresora',113),
('Varios','Pad Mouse',114),
('Varios','Bolsas RX''S',115),
('Varios','Guantes calibre 35',116),
('Varios','Motitas de algodon',117),
('Varios','Removedor',118),
('Aseo','Esponjas',119),
('Aseo','Papel higiénico (Rollos)',120),
('Aseo','Citronella',121),
('Aseo','Fabuloso',122),
('Aseo','Pop it',123),
('Aseo','1A',124),
('Aseo','Frotex',125),
('Aseo','Aromatizante (Baño)',126),
('Aseo','Limpiavidrios',127),
('Aseo','Pato tanque',128),
('Aseo','Lavaloza',129),
('Aseo','Toallas Wypall',130),
('Aseo','Brilla Metal',131),
('Aseo','Trapeadora',132),
('Aseo','Jabon dispensador Tork',133),
('Aseo','Toallas de mano dispensador Tork',134),
('Cafetería','Café',135),
('Cafetería','Aromáticas',136),
('Papelería','Resma carta',137),
('Papelería','Resma media carta',138),
('Papelería','Lapiceros (Caja*12)',139),
('Papelería','Resaltador',140),
('Papelería','Sharpie Delgado (Micropunta)',141),
('Papelería','Sharpie Grueso',142),
('Papelería','Clips (Bolsa)',143),
('Papelería','Ganchos para cosedora',144),
('Papelería','Clips para carpeta',145),
('Papelería','Protectores de hojas',146),
('Papelería','Recomendaciones aparatología fija',147),
('Papelería','Recomendaciones aparatología Removible',148),
('Papelería','Recomendaciones aparatología Extraoral',149),
('Papelería','Recomendaciones CTZ',150),
('Papelería','Métodos de pago',151),
('Papelería','Servicrédito',152),
('Papelería','Recomendaciones Restauraciones',153),
('Papelería','Recetarios',154),
('Papelería','Sedación óxido nitroso',155),
('Papelería','Sedación Intravenosa',156),
('Papelería','Cremas dentales (recomendaciones)',157),
('Papelería','Libretas Dentilandia',158),
('Papelería','Tarjetas Dentilandia',159),
('Papelería','Stickers Semaforización',160),
('Papelería','Cinta de enmascarar',161),
('Papelería','Cinta transparente',162),
('Papelería','Recibos de caja menor',163),
('Sin categoría','Piedra pomez',164),
('Sin categoría','Detergente Liquido D1',165),
('Sin categoría','Lubricante para pieza de mano',166),
('Sin categoría','Forcep 150 pediatrico',167),
('Sin categoría','Jeringa carpull',168),
('Sin categoría','Bloque de mordida azul talla M con refuerzo metalico',169),
('Sin categoría','Gafas transparentes de proteccion',170),
('Sin categoría','Guantes de Vinilo Talla L',171),
('Sin categoría','Carpeta AZ',172);
